# Generated by Django 5.2.5 on 2025-09-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('cred_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=255)),
                ('dept_type', models.CharField(max_length=255)),
                ('dept_head', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('contact', models.BigIntegerField()),
                ('email_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('work_order_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('uom', models.CharField(max_length=255)),
                ('amount_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'PurchaseItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierData',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gstn_no', models.CharField(max_length=255)),
                ('contact_no', models.BigIntegerField()),
                ('contact_person', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_acc_no', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SupplierData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('upload_date', models.DateField()),
                ('expense_date', models.DateField()),
                ('voucher_type', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Voucher',
                'managed': False,
            },
        ),
    ]
